title: Arindam Paul
description: My f***ing website

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 6

navigation1:
 - title: Home
   url: /index.html
 - title: Personal
   url: /about
 - title: Projects
   url: /projects
 - title: Publications
   url: /publications



navigation2:
 - title: Contact
   url: /contact

social:
   github: paularindam
   twitter: arndmPaul
   linkedin: arndmpaul
   facebook: arindampaul.bits
   quora: Arindam-Paul-3
   email: arindam.paul@eecs.northwestern.edu

google_analytics:
