title: Arindam Paul
description: My website

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
port: 4445
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 6

navigation1:
 - title: Home
   url: /index.html
 - title: Portfolio
   url: /projects
 - title: Publications
   url: /publications
 - title: CV
   url: /vitae
 - title: Personal
   url: /about


navigation2:
 - title: Contact
   url: /contact



social:
   github: paularindam
   twitter: arndmPaul
   linkedin: arndmpaul
   facebook: arindampaul.bits
   quora: Arindam-Paul-3
   researchgate: Arindam_Paul5
   academia: ArindamPaul
   scholar: iGPYZD0AAAAJ
   bitbucket: paulappl
   email: arindam.paul@eecs.northwestern.edu

google_analytics:
