title: Arindam Paul
description: My website

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
port: 4000
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 6

navigation:
 - title: Home
   url: /index.html
 - title: Personal
   url: /about
 - title: Publications
   url: /publications
 - title: Vitae
   url: /vitae
 - title: Contact
   url: /contact



social:
   github: paularindam
   linkedin: arndmpaul
   researchgate: Arindam_Paul5
   scholar: iGPYZD0AAAAJ
   email: arindampaul.bits@gmail.com

google_analytics:
