title: Arindam Paul
description: My f***ing website

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /about
 - title: Contact
   url: /contact



social:
   github: paularindam
   twitter: arndmPaul
   linkedin: arndmpaul
   facebook: arindampaul.bits
   email: arindam.paul@eecs.northwestern.edu

google_analytics:
